spring:
#  mvc:
#    static-path-pattern: /res/**   这个会导致welcome page功能失效
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能
    contentnegotiation:
      favor-parameter: true  #开启请求参数内容协商模式